# -*- coding: utf-8 -*-
"""Oasis_DS_02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vtF6igXGXUgBrYaCBL-B0TCaKXofpmFj
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as pt
import seaborn as sb

data_unemp = pd.read_csv("/content/Untitled Folder/Unemployment_Rate_upto_11_2020.csv")

data_unemp

data_unemp.head(20)

data_unemp.tail(30)

data_unemp.info()

data_unemp.describe()

data_unemp.size

data_unemp.shape

data_unemp.columns

data_unemp.isnull().sum()

#for checking duplicacy
data_unemp.duplicated().sum()

data_unemp=pd.DataFrame(data_unemp)
y=data_unemp[' Estimated Unemployment Rate (%)']
x=data_unemp['Region']
pr= pt.figure(figsize=(40, 15))
pt.xlabel("States",fontweight='bold',fontsize=20)
pt.ylabel("Estimated Unemployment rate",fontweight='bold',fontsize=20)
pt.xticks(fontweight='bold',rotation='vertical',fontsize=20)
pt.bar(x,y, color='r',align='center')

# State wise rate of unemplyement

u_emp= data_unemp[['Region',' Estimated Unemployment Rate (%)']].groupby('Region').sum().sort_values(by=' Estimated Unemployment Rate (%)', ascending =False)
u_emp

import plotly.express as pl

unemp_data= data_unemp[["Region", "Region.1", ' Estimated Unemployment Rate (%)']]
figure= pl.sunburst(unemp_data, path=["Region.1", "Region"],values=' Estimated Unemployment Rate (%)',width=700, height=700, color_continuous_scale="Rdy1Gn",title="Rate of unemployment in India")
figure.show()

pt.figure(figsize=(8,4))
sb.heatmap(data_unemp.corr())
pt.show()

pt.figure(figsize=(12,10))
pt.title('Unemployment In India')
sb.histplot(x=' Estimated Unemployment Rate (%)', hue="Region.1", data=data_unemp)
pt.show()

pt.figure(figsize=(12,10))
pt.title('Unemployment In India State Wise')
sb.histplot(x=' Estimated Unemployment Rate (%)', hue="Region", data=data_unemp)
pt.show()

